SWDEV-429037 - Automatically install amdsmi python lib with package
Signed-off-by: Maisam Arif <maisarif@amd.com>
Change-Id: I9c8c1335982ebd61a29da6f66c635f0a97d95f6e


[ROCm/amdsmi commit: c2e12feb6a0499c417633317be4a64c1d61a1c50]

diff --git a/DEBIAN/prerm.in b/DEBIAN/prerm.in
--- a/DEBIAN/prerm.in
+++ b/DEBIAN/prerm.in
@@ -33,11 +33,36 @@ return_logrotateToOrigConfig() {
   fi
 }
 
+rm_python_lib() {
+  # get python version
+  local python3_minor_version=$(python3 -c 'import sys;print(sys.version_info.minor)')
+  if [ $? -ne 0 ]; then
+    echo "[WARNING] Could not determine python version. "\
+      "AMD-SMI python library will not be uninstalled."
+    return
+  fi
+
+  # check if python version is supported
+  if [ "$python3_minor_version" -lt 6 ]; then
+    echo "[INFO] AMD-SMI python library is not supported on python version 3.$python3_minor_version. "\
+      "AMD-SMI python library will not be uninstalled."
+    return
+  fi
+
+  python3 -m pip uninstall amdsmi --yes
+  python3 -m pip show amdsmi
+  if [ $? -ne 1 ]; then
+    echo "[WARNING] AMD-SMI python library (amdsmi) is still installed. "\
+      "Check post install to ensure version is correct"
+    return
+  fi
+}
 
 case "$1" in
   ( remove | upgrade)
     # remove old gpuv-smi symlink
     rm -f @CPACK_PACKAGING_INSTALL_PREFIX@/bin/gpuv-smi &> /dev/null
+    rm_python_lib
     rm_ldconfig
     rm_pyc
     rm_logFolder
